// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mcpconfig/v1/config_service.proto

package mcpconfigv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConvertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source config file path. Format is inferred from the path.
	In string `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	// Target config file path. Format is inferred from the path.
	Out           string `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_mcpconfig_v1_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcpconfig_v1_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_mcpconfig_v1_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConvertRequest) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *ConvertRequest) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

type ConvertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of servers converted.
	ServerCount int32 `protobuf:"varint,1,opt,name=server_count,json=serverCount,proto3" json:"server_count,omitempty"`
	// The file path where the target config was written.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Human-readable summary of the conversion.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_mcpconfig_v1_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mcpconfig_v1_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_mcpconfig_v1_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConvertResponse) GetServerCount() int32 {
	if x != nil {
		return x.ServerCount
	}
	return 0
}

func (x *ConvertResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConvertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mcpconfig_v1_config_service_proto protoreflect.FileDescriptor

const file_mcpconfig_v1_config_service_proto_rawDesc = "" +
	"\n" +
	"!mcpconfig/v1/config_service.proto\x12\fmcpconfig.v1\"2\n" +
	"\x0eConvertRequest\x12\x0e\n" +
	"\x02in\x18\x01 \x01(\tR\x02in\x12\x10\n" +
	"\x03out\x18\x02 \x01(\tR\x03out\"b\n" +
	"\x0fConvertResponse\x12!\n" +
	"\fserver_count\x18\x01 \x01(\x05R\vserverCount\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2W\n" +
	"\rConfigService\x12F\n" +
	"\aConvert\x12\x1c.mcpconfig.v1.ConvertRequest\x1a\x1d.mcpconfig.v1.ConvertResponseB\xba\x01\n" +
	"\x10com.mcpconfig.v1B\x12ConfigServiceProtoP\x01ZAgithub.com/jim-technologies/invariantmcp/mcpconfig/v1;mcpconfigv1\xa2\x02\x03MXX\xaa\x02\fMcpconfig.V1\xca\x02\fMcpconfig\\V1\xe2\x02\x18Mcpconfig\\V1\\GPBMetadata\xea\x02\rMcpconfig::V1b\x06proto3"

var (
	file_mcpconfig_v1_config_service_proto_rawDescOnce sync.Once
	file_mcpconfig_v1_config_service_proto_rawDescData []byte
)

func file_mcpconfig_v1_config_service_proto_rawDescGZIP() []byte {
	file_mcpconfig_v1_config_service_proto_rawDescOnce.Do(func() {
		file_mcpconfig_v1_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcpconfig_v1_config_service_proto_rawDesc), len(file_mcpconfig_v1_config_service_proto_rawDesc)))
	})
	return file_mcpconfig_v1_config_service_proto_rawDescData
}

var file_mcpconfig_v1_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mcpconfig_v1_config_service_proto_goTypes = []any{
	(*ConvertRequest)(nil),  // 0: mcpconfig.v1.ConvertRequest
	(*ConvertResponse)(nil), // 1: mcpconfig.v1.ConvertResponse
}
var file_mcpconfig_v1_config_service_proto_depIdxs = []int32{
	0, // 0: mcpconfig.v1.ConfigService.Convert:input_type -> mcpconfig.v1.ConvertRequest
	1, // 1: mcpconfig.v1.ConfigService.Convert:output_type -> mcpconfig.v1.ConvertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mcpconfig_v1_config_service_proto_init() }
func file_mcpconfig_v1_config_service_proto_init() {
	if File_mcpconfig_v1_config_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcpconfig_v1_config_service_proto_rawDesc), len(file_mcpconfig_v1_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcpconfig_v1_config_service_proto_goTypes,
		DependencyIndexes: file_mcpconfig_v1_config_service_proto_depIdxs,
		MessageInfos:      file_mcpconfig_v1_config_service_proto_msgTypes,
	}.Build()
	File_mcpconfig_v1_config_service_proto = out.File
	file_mcpconfig_v1_config_service_proto_goTypes = nil
	file_mcpconfig_v1_config_service_proto_depIdxs = nil
}
